/* tslint:disable */
/* eslint-disable */
/**
 * Javis smart stock analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1Balance
 */
export interface V1Balance {
    /**
     * 
     * @type {string}
     * @memberof V1Balance
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof V1Balance
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof V1Balance
     */
    updatedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof V1Balance
     */
    balance?: number;
    /**
     * 
     * @type {number}
     * @memberof V1Balance
     */
    available?: number;
    /**
     * 
     * @type {number}
     * @memberof V1Balance
     */
    pending?: number;
}

/**
 * Check if a given object implements the V1Balance interface.
 */
export function instanceOfV1Balance(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1BalanceFromJSON(json: any): V1Balance {
    return V1BalanceFromJSONTyped(json, false);
}

export function V1BalanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1Balance {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'balance': !exists(json, 'balance') ? undefined : json['balance'],
        'available': !exists(json, 'available') ? undefined : json['available'],
        'pending': !exists(json, 'pending') ? undefined : json['pending'],
    };
}

export function V1BalanceToJSON(value?: V1Balance | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'balance': value.balance,
        'available': value.available,
        'pending': value.pending,
    };
}

