/* tslint:disable */
/* eslint-disable */
/**
 * Javis smart stock analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1CreateUserRequest
 */
export interface V1CreateUserRequest {
    /**
     * 
     * @type {string}
     * @memberof V1CreateUserRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateUserRequest
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateUserRequest
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateUserRequest
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateUserRequest
     */
    password?: string;
}

/**
 * Check if a given object implements the V1CreateUserRequest interface.
 */
export function instanceOfV1CreateUserRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1CreateUserRequestFromJSON(json: any): V1CreateUserRequest {
    return V1CreateUserRequestFromJSONTyped(json, false);
}

export function V1CreateUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CreateUserRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'password': !exists(json, 'password') ? undefined : json['password'],
    };
}

export function V1CreateUserRequestToJSON(value?: V1CreateUserRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'phone': value.phone,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'password': value.password,
    };
}

