/* tslint:disable */
/* eslint-disable */
/**
 * Javis smart stock analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1DeletePickedStocksResponse
 */
export interface V1DeletePickedStocksResponse {
    /**
     * 
     * @type {boolean}
     * @memberof V1DeletePickedStocksResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof V1DeletePickedStocksResponse
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof V1DeletePickedStocksResponse
     */
    errorMessage?: string;
    /**
     * 
     * @type {string}
     * @memberof V1DeletePickedStocksResponse
     */
    errorCode?: string;
}

/**
 * Check if a given object implements the V1DeletePickedStocksResponse interface.
 */
export function instanceOfV1DeletePickedStocksResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1DeletePickedStocksResponseFromJSON(json: any): V1DeletePickedStocksResponse {
    return V1DeletePickedStocksResponseFromJSONTyped(json, false);
}

export function V1DeletePickedStocksResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1DeletePickedStocksResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'errorMessage': !exists(json, 'errorMessage') ? undefined : json['errorMessage'],
        'errorCode': !exists(json, 'errorCode') ? undefined : json['errorCode'],
    };
}

export function V1DeletePickedStocksResponseToJSON(value?: V1DeletePickedStocksResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'status': value.status,
        'errorMessage': value.errorMessage,
        'errorCode': value.errorCode,
    };
}

