/* tslint:disable */
/* eslint-disable */
/**
 * Javis smart stock analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1GetStakeConcentrationRequest
 */
export interface V1GetStakeConcentrationRequest {
    /**
     * 
     * @type {string}
     * @memberof V1GetStakeConcentrationRequest
     */
    stockID?: string;
    /**
     * 
     * @type {string}
     * @memberof V1GetStakeConcentrationRequest
     */
    date?: string;
}

/**
 * Check if a given object implements the V1GetStakeConcentrationRequest interface.
 */
export function instanceOfV1GetStakeConcentrationRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1GetStakeConcentrationRequestFromJSON(json: any): V1GetStakeConcentrationRequest {
    return V1GetStakeConcentrationRequestFromJSONTyped(json, false);
}

export function V1GetStakeConcentrationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1GetStakeConcentrationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stockID': !exists(json, 'stockID') ? undefined : json['stockID'],
        'date': !exists(json, 'date') ? undefined : json['date'],
    };
}

export function V1GetStakeConcentrationRequestToJSON(value?: V1GetStakeConcentrationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stockID': value.stockID,
        'date': value.date,
    };
}

