/* tslint:disable */
/* eslint-disable */
/**
 * Javis smart stock analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1Balance } from './V1Balance';
import {
    V1BalanceFromJSON,
    V1BalanceFromJSONTyped,
    V1BalanceToJSON,
} from './V1Balance';

/**
 * 
 * @export
 * @interface V1GetBalanceResponse
 */
export interface V1GetBalanceResponse {
    /**
     * 
     * @type {V1Balance}
     * @memberof V1GetBalanceResponse
     */
    balance?: V1Balance;
}

/**
 * Check if a given object implements the V1GetBalanceResponse interface.
 */
export function instanceOfV1GetBalanceResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1GetBalanceResponseFromJSON(json: any): V1GetBalanceResponse {
    return V1GetBalanceResponseFromJSONTyped(json, false);
}

export function V1GetBalanceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1GetBalanceResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'balance': !exists(json, 'balance') ? undefined : V1BalanceFromJSON(json['balance']),
    };
}

export function V1GetBalanceResponseToJSON(value?: V1GetBalanceResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'balance': V1BalanceToJSON(value.balance),
    };
}

