/* tslint:disable */
/* eslint-disable */
/**
 * Javis smart stock analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1InsertPickedStocksRequest
 */
export interface V1InsertPickedStocksRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof V1InsertPickedStocksRequest
     */
    stockIDs?: Array<string>;
}

/**
 * Check if a given object implements the V1InsertPickedStocksRequest interface.
 */
export function instanceOfV1InsertPickedStocksRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1InsertPickedStocksRequestFromJSON(json: any): V1InsertPickedStocksRequest {
    return V1InsertPickedStocksRequestFromJSONTyped(json, false);
}

export function V1InsertPickedStocksRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1InsertPickedStocksRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stockIDs': !exists(json, 'stockIDs') ? undefined : json['stockIDs'],
    };
}

export function V1InsertPickedStocksRequestToJSON(value?: V1InsertPickedStocksRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stockIDs': value.stockIDs,
    };
}

