/* tslint:disable */
/* eslint-disable */
/**
 * Javis smart stock analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1ListThreePrimarySearchParams
 */
export interface V1ListThreePrimarySearchParams {
    /**
     * 
     * @type {string}
     * @memberof V1ListThreePrimarySearchParams
     */
    stockID?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ListThreePrimarySearchParams
     */
    start?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ListThreePrimarySearchParams
     */
    end?: string;
}

/**
 * Check if a given object implements the V1ListThreePrimarySearchParams interface.
 */
export function instanceOfV1ListThreePrimarySearchParams(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1ListThreePrimarySearchParamsFromJSON(json: any): V1ListThreePrimarySearchParams {
    return V1ListThreePrimarySearchParamsFromJSONTyped(json, false);
}

export function V1ListThreePrimarySearchParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ListThreePrimarySearchParams {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stockID': !exists(json, 'stockID') ? undefined : json['stockID'],
        'start': !exists(json, 'start') ? undefined : json['start'],
        'end': !exists(json, 'end') ? undefined : json['end'],
    };
}

export function V1ListThreePrimarySearchParamsToJSON(value?: V1ListThreePrimarySearchParams | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stockID': value.stockID,
        'start': value.start,
        'end': value.end,
    };
}

