/* tslint:disable */
/* eslint-disable */
/**
 * Javis smart stock analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1ListStockSearchParams } from './V1ListStockSearchParams';
import {
    V1ListStockSearchParamsFromJSON,
    V1ListStockSearchParamsFromJSONTyped,
    V1ListStockSearchParamsToJSON,
} from './V1ListStockSearchParams';

/**
 * 
 * @export
 * @interface V1ListStockRequest
 */
export interface V1ListStockRequest {
    /**
     * 
     * @type {number}
     * @memberof V1ListStockRequest
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof V1ListStockRequest
     */
    limit?: number;
    /**
     * 
     * @type {V1ListStockSearchParams}
     * @memberof V1ListStockRequest
     */
    searchParams?: V1ListStockSearchParams;
}

/**
 * Check if a given object implements the V1ListStockRequest interface.
 */
export function instanceOfV1ListStockRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1ListStockRequestFromJSON(json: any): V1ListStockRequest {
    return V1ListStockRequestFromJSONTyped(json, false);
}

export function V1ListStockRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ListStockRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'offset': !exists(json, 'offset') ? undefined : json['offset'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'searchParams': !exists(json, 'searchParams') ? undefined : V1ListStockSearchParamsFromJSON(json['searchParams']),
    };
}

export function V1ListStockRequestToJSON(value?: V1ListStockRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'offset': value.offset,
        'limit': value.limit,
        'searchParams': V1ListStockSearchParamsToJSON(value.searchParams),
    };
}

