/* tslint:disable */
/* eslint-disable */
/**
 * Javis smart stock analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1ListOrderSearchParams } from './V1ListOrderSearchParams';
import {
    V1ListOrderSearchParamsFromJSON,
    V1ListOrderSearchParamsFromJSONTyped,
    V1ListOrderSearchParamsToJSON,
} from './V1ListOrderSearchParams';

/**
 * 
 * @export
 * @interface V1ListOrderRequest
 */
export interface V1ListOrderRequest {
    /**
     * 
     * @type {number}
     * @memberof V1ListOrderRequest
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof V1ListOrderRequest
     */
    limit?: number;
    /**
     * 
     * @type {V1ListOrderSearchParams}
     * @memberof V1ListOrderRequest
     */
    searchParams?: V1ListOrderSearchParams;
}

/**
 * Check if a given object implements the V1ListOrderRequest interface.
 */
export function instanceOfV1ListOrderRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1ListOrderRequestFromJSON(json: any): V1ListOrderRequest {
    return V1ListOrderRequestFromJSONTyped(json, false);
}

export function V1ListOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ListOrderRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'offset': !exists(json, 'offset') ? undefined : json['offset'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'searchParams': !exists(json, 'searchParams') ? undefined : V1ListOrderSearchParamsFromJSON(json['searchParams']),
    };
}

export function V1ListOrderRequestToJSON(value?: V1ListOrderRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'offset': value.offset,
        'limit': value.limit,
        'searchParams': V1ListOrderSearchParamsToJSON(value.searchParams),
    };
}

