/* tslint:disable */
/* eslint-disable */
/**
 * Javis smart stock analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1ListSelectionRequest
 */
export interface V1ListSelectionRequest {
    /**
     * 
     * @type {string}
     * @memberof V1ListSelectionRequest
     */
    date?: string;
    /**
     * 
     * @type {boolean}
     * @memberof V1ListSelectionRequest
     */
    strict?: boolean;
}

/**
 * Check if a given object implements the V1ListSelectionRequest interface.
 */
export function instanceOfV1ListSelectionRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1ListSelectionRequestFromJSON(json: any): V1ListSelectionRequest {
    return V1ListSelectionRequestFromJSONTyped(json, false);
}

export function V1ListSelectionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ListSelectionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'date': !exists(json, 'date') ? undefined : json['date'],
        'strict': !exists(json, 'strict') ? undefined : json['strict'],
    };
}

export function V1ListSelectionRequestToJSON(value?: V1ListSelectionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': value.date,
        'strict': value.strict,
    };
}

