/* tslint:disable */
/* eslint-disable */
/**
 * Javis smart stock analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1ThreePrimary } from './V1ThreePrimary';
import {
    V1ThreePrimaryFromJSON,
    V1ThreePrimaryFromJSONTyped,
    V1ThreePrimaryToJSON,
} from './V1ThreePrimary';

/**
 * 
 * @export
 * @interface V1ListThreePrimaryResponse
 */
export interface V1ListThreePrimaryResponse {
    /**
     * 
     * @type {number}
     * @memberof V1ListThreePrimaryResponse
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof V1ListThreePrimaryResponse
     */
    limit?: number;
    /**
     * 
     * @type {string}
     * @memberof V1ListThreePrimaryResponse
     */
    totalCount?: string;
    /**
     * 
     * @type {Array<V1ThreePrimary>}
     * @memberof V1ListThreePrimaryResponse
     */
    entries?: Array<V1ThreePrimary>;
}

/**
 * Check if a given object implements the V1ListThreePrimaryResponse interface.
 */
export function instanceOfV1ListThreePrimaryResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1ListThreePrimaryResponseFromJSON(json: any): V1ListThreePrimaryResponse {
    return V1ListThreePrimaryResponseFromJSONTyped(json, false);
}

export function V1ListThreePrimaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ListThreePrimaryResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'offset': !exists(json, 'offset') ? undefined : json['offset'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'entries': !exists(json, 'entries') ? undefined : ((json['entries'] as Array<any>).map(V1ThreePrimaryFromJSON)),
    };
}

export function V1ListThreePrimaryResponseToJSON(value?: V1ListThreePrimaryResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'offset': value.offset,
        'limit': value.limit,
        'totalCount': value.totalCount,
        'entries': value.entries === undefined ? undefined : ((value.entries as Array<any>).map(V1ThreePrimaryToJSON)),
    };
}

