/* tslint:disable */
/* eslint-disable */
/**
 * Javis smart stock analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1User } from './V1User';
import {
    V1UserFromJSON,
    V1UserFromJSONTyped,
    V1UserToJSON,
} from './V1User';

/**
 * 
 * @export
 * @interface V1ListUsersResponse
 */
export interface V1ListUsersResponse {
    /**
     * 
     * @type {number}
     * @memberof V1ListUsersResponse
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof V1ListUsersResponse
     */
    limit?: number;
    /**
     * 
     * @type {string}
     * @memberof V1ListUsersResponse
     */
    totalCount?: string;
    /**
     * 
     * @type {Array<V1User>}
     * @memberof V1ListUsersResponse
     */
    entries?: Array<V1User>;
}

/**
 * Check if a given object implements the V1ListUsersResponse interface.
 */
export function instanceOfV1ListUsersResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1ListUsersResponseFromJSON(json: any): V1ListUsersResponse {
    return V1ListUsersResponseFromJSONTyped(json, false);
}

export function V1ListUsersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ListUsersResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'offset': !exists(json, 'offset') ? undefined : json['offset'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'entries': !exists(json, 'entries') ? undefined : ((json['entries'] as Array<any>).map(V1UserFromJSON)),
    };
}

export function V1ListUsersResponseToJSON(value?: V1ListUsersResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'offset': value.offset,
        'limit': value.limit,
        'totalCount': value.totalCount,
        'entries': value.entries === undefined ? undefined : ((value.entries as Array<any>).map(V1UserToJSON)),
    };
}

