/* tslint:disable */
/* eslint-disable */
/**
 * Javis smart stock analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1DailyClose } from './V1DailyClose';
import {
    V1DailyCloseFromJSON,
    V1DailyCloseFromJSONTyped,
    V1DailyCloseToJSON,
} from './V1DailyClose';

/**
 * 
 * @export
 * @interface V1ListDailyCloseResponse
 */
export interface V1ListDailyCloseResponse {
    /**
     * 
     * @type {number}
     * @memberof V1ListDailyCloseResponse
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof V1ListDailyCloseResponse
     */
    limit?: number;
    /**
     * 
     * @type {string}
     * @memberof V1ListDailyCloseResponse
     */
    totalCount?: string;
    /**
     * 
     * @type {Array<V1DailyClose>}
     * @memberof V1ListDailyCloseResponse
     */
    entries?: Array<V1DailyClose>;
}

/**
 * Check if a given object implements the V1ListDailyCloseResponse interface.
 */
export function instanceOfV1ListDailyCloseResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1ListDailyCloseResponseFromJSON(json: any): V1ListDailyCloseResponse {
    return V1ListDailyCloseResponseFromJSONTyped(json, false);
}

export function V1ListDailyCloseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ListDailyCloseResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'offset': !exists(json, 'offset') ? undefined : json['offset'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'entries': !exists(json, 'entries') ? undefined : ((json['entries'] as Array<any>).map(V1DailyCloseFromJSON)),
    };
}

export function V1ListDailyCloseResponseToJSON(value?: V1ListDailyCloseResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'offset': value.offset,
        'limit': value.limit,
        'totalCount': value.totalCount,
        'entries': value.entries === undefined ? undefined : ((value.entries as Array<any>).map(V1DailyCloseToJSON)),
    };
}

