/* tslint:disable */
/* eslint-disable */
/**
 * Javis smart stock analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1Selection } from './V1Selection';
import {
    V1SelectionFromJSON,
    V1SelectionFromJSONTyped,
    V1SelectionToJSON,
} from './V1Selection';

/**
 * 
 * @export
 * @interface V1ListSelectionResponse
 */
export interface V1ListSelectionResponse {
    /**
     * 
     * @type {Array<V1Selection>}
     * @memberof V1ListSelectionResponse
     */
    entries?: Array<V1Selection>;
}

/**
 * Check if a given object implements the V1ListSelectionResponse interface.
 */
export function instanceOfV1ListSelectionResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1ListSelectionResponseFromJSON(json: any): V1ListSelectionResponse {
    return V1ListSelectionResponseFromJSONTyped(json, false);
}

export function V1ListSelectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ListSelectionResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'entries': !exists(json, 'entries') ? undefined : ((json['entries'] as Array<any>).map(V1SelectionFromJSON)),
    };
}

export function V1ListSelectionResponseToJSON(value?: V1ListSelectionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'entries': value.entries === undefined ? undefined : ((value.entries as Array<any>).map(V1SelectionToJSON)),
    };
}

