/* tslint:disable */
/* eslint-disable */
/**
 * Javis smart stock analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1ListOrderSearchParams
 */
export interface V1ListOrderSearchParams {
    /**
     * 
     * @type {Array<string>}
     * @memberof V1ListOrderSearchParams
     */
    stockIDs?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof V1ListOrderSearchParams
     */
    exchangeMonth?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ListOrderSearchParams
     */
    status?: string;
}

/**
 * Check if a given object implements the V1ListOrderSearchParams interface.
 */
export function instanceOfV1ListOrderSearchParams(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1ListOrderSearchParamsFromJSON(json: any): V1ListOrderSearchParams {
    return V1ListOrderSearchParamsFromJSONTyped(json, false);
}

export function V1ListOrderSearchParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ListOrderSearchParams {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stockIDs': !exists(json, 'stockIDs') ? undefined : json['stockIDs'],
        'exchangeMonth': !exists(json, 'exchangeMonth') ? undefined : json['exchangeMonth'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function V1ListOrderSearchParamsToJSON(value?: V1ListOrderSearchParams | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stockIDs': value.stockIDs,
        'exchangeMonth': value.exchangeMonth,
        'status': value.status,
    };
}

