/* tslint:disable */
/* eslint-disable */
/**
 * Javis smart stock analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1ListCategoriesResponse
 */
export interface V1ListCategoriesResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof V1ListCategoriesResponse
     */
    entries?: Array<string>;
}

/**
 * Check if a given object implements the V1ListCategoriesResponse interface.
 */
export function instanceOfV1ListCategoriesResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1ListCategoriesResponseFromJSON(json: any): V1ListCategoriesResponse {
    return V1ListCategoriesResponseFromJSONTyped(json, false);
}

export function V1ListCategoriesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ListCategoriesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'entries': !exists(json, 'entries') ? undefined : json['entries'],
    };
}

export function V1ListCategoriesResponseToJSON(value?: V1ListCategoriesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'entries': value.entries,
    };
}

