/* tslint:disable */
/* eslint-disable */
/**
 * Javis smart stock analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1Stock } from './V1Stock';
import {
    V1StockFromJSON,
    V1StockFromJSONTyped,
    V1StockToJSON,
} from './V1Stock';

/**
 * 
 * @export
 * @interface V1ListStockResponse
 */
export interface V1ListStockResponse {
    /**
     * 
     * @type {number}
     * @memberof V1ListStockResponse
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof V1ListStockResponse
     */
    limit?: number;
    /**
     * 
     * @type {string}
     * @memberof V1ListStockResponse
     */
    totalCount?: string;
    /**
     * 
     * @type {Array<V1Stock>}
     * @memberof V1ListStockResponse
     */
    entries?: Array<V1Stock>;
}

/**
 * Check if a given object implements the V1ListStockResponse interface.
 */
export function instanceOfV1ListStockResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1ListStockResponseFromJSON(json: any): V1ListStockResponse {
    return V1ListStockResponseFromJSONTyped(json, false);
}

export function V1ListStockResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ListStockResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'offset': !exists(json, 'offset') ? undefined : json['offset'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'entries': !exists(json, 'entries') ? undefined : ((json['entries'] as Array<any>).map(V1StockFromJSON)),
    };
}

export function V1ListStockResponseToJSON(value?: V1ListStockResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'offset': value.offset,
        'limit': value.limit,
        'totalCount': value.totalCount,
        'entries': value.entries === undefined ? undefined : ((value.entries as Array<any>).map(V1StockToJSON)),
    };
}

