/* tslint:disable */
/* eslint-disable */
/**
 * Javis smart stock analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1LoginRequest
 */
export interface V1LoginRequest {
    /**
     * 
     * @type {string}
     * @memberof V1LoginRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof V1LoginRequest
     */
    password?: string;
}

/**
 * Check if a given object implements the V1LoginRequest interface.
 */
export function instanceOfV1LoginRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1LoginRequestFromJSON(json: any): V1LoginRequest {
    return V1LoginRequestFromJSONTyped(json, false);
}

export function V1LoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1LoginRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
        'password': !exists(json, 'password') ? undefined : json['password'],
    };
}

export function V1LoginRequestToJSON(value?: V1LoginRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
    };
}

