/* tslint:disable */
/* eslint-disable */
/**
 * Javis smart stock analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1Selection
 */
export interface V1Selection {
    /**
     * 
     * @type {string}
     * @memberof V1Selection
     */
    stockID?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Selection
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Selection
     */
    category?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Selection
     */
    date?: string;
    /**
     * 
     * @type {number}
     * @memberof V1Selection
     */
    concentration1?: number;
    /**
     * 
     * @type {number}
     * @memberof V1Selection
     */
    concentration5?: number;
    /**
     * 
     * @type {number}
     * @memberof V1Selection
     */
    concentration10?: number;
    /**
     * 
     * @type {number}
     * @memberof V1Selection
     */
    concentration20?: number;
    /**
     * 
     * @type {number}
     * @memberof V1Selection
     */
    concentration60?: number;
    /**
     * 
     * @type {number}
     * @memberof V1Selection
     */
    volume?: number;
    /**
     * 
     * @type {number}
     * @memberof V1Selection
     */
    foreign?: number;
    /**
     * 
     * @type {number}
     * @memberof V1Selection
     */
    trust?: number;
    /**
     * 
     * @type {number}
     * @memberof V1Selection
     */
    dealer?: number;
    /**
     * 
     * @type {number}
     * @memberof V1Selection
     */
    hedging?: number;
    /**
     * 
     * @type {number}
     * @memberof V1Selection
     */
    open?: number;
    /**
     * 
     * @type {number}
     * @memberof V1Selection
     */
    close?: number;
    /**
     * 
     * @type {number}
     * @memberof V1Selection
     */
    high?: number;
    /**
     * 
     * @type {number}
     * @memberof V1Selection
     */
    low?: number;
    /**
     * 
     * @type {number}
     * @memberof V1Selection
     */
    diff?: number;
    /**
     * 
     * @type {number}
     * @memberof V1Selection
     */
    trust10?: number;
    /**
     * 
     * @type {number}
     * @memberof V1Selection
     */
    foreign10?: number;
    /**
     * 
     * @type {number}
     * @memberof V1Selection
     */
    quoteChange?: number;
}

/**
 * Check if a given object implements the V1Selection interface.
 */
export function instanceOfV1Selection(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1SelectionFromJSON(json: any): V1Selection {
    return V1SelectionFromJSONTyped(json, false);
}

export function V1SelectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1Selection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stockID': !exists(json, 'stockID') ? undefined : json['stockID'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'category': !exists(json, 'category') ? undefined : json['category'],
        'date': !exists(json, 'date') ? undefined : json['date'],
        'concentration1': !exists(json, 'concentration1') ? undefined : json['concentration1'],
        'concentration5': !exists(json, 'concentration5') ? undefined : json['concentration5'],
        'concentration10': !exists(json, 'concentration10') ? undefined : json['concentration10'],
        'concentration20': !exists(json, 'concentration20') ? undefined : json['concentration20'],
        'concentration60': !exists(json, 'concentration60') ? undefined : json['concentration60'],
        'volume': !exists(json, 'volume') ? undefined : json['volume'],
        'foreign': !exists(json, 'foreign') ? undefined : json['foreign'],
        'trust': !exists(json, 'trust') ? undefined : json['trust'],
        'dealer': !exists(json, 'dealer') ? undefined : json['dealer'],
        'hedging': !exists(json, 'hedging') ? undefined : json['hedging'],
        'open': !exists(json, 'open') ? undefined : json['open'],
        'close': !exists(json, 'close') ? undefined : json['close'],
        'high': !exists(json, 'high') ? undefined : json['high'],
        'low': !exists(json, 'low') ? undefined : json['low'],
        'diff': !exists(json, 'diff') ? undefined : json['diff'],
        'trust10': !exists(json, 'trust10') ? undefined : json['trust10'],
        'foreign10': !exists(json, 'foreign10') ? undefined : json['foreign10'],
        'quoteChange': !exists(json, 'quoteChange') ? undefined : json['quoteChange'],
    };
}

export function V1SelectionToJSON(value?: V1Selection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stockID': value.stockID,
        'name': value.name,
        'category': value.category,
        'date': value.date,
        'concentration1': value.concentration1,
        'concentration5': value.concentration5,
        'concentration10': value.concentration10,
        'concentration20': value.concentration20,
        'concentration60': value.concentration60,
        'volume': value.volume,
        'foreign': value.foreign,
        'trust': value.trust,
        'dealer': value.dealer,
        'hedging': value.hedging,
        'open': value.open,
        'close': value.close,
        'high': value.high,
        'low': value.low,
        'diff': value.diff,
        'trust10': value.trust10,
        'foreign10': value.foreign10,
        'quoteChange': value.quoteChange,
    };
}

