/* tslint:disable */
/* eslint-disable */
/**
 * Javis smart stock analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1Stock
 */
export interface V1Stock {
    /**
     * 
     * @type {string}
     * @memberof V1Stock
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof V1Stock
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof V1Stock
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof V1Stock
     */
    deletedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof V1Stock
     */
    stockID?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Stock
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Stock
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Stock
     */
    category?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Stock
     */
    market?: string;
}

/**
 * Check if a given object implements the V1Stock interface.
 */
export function instanceOfV1Stock(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1StockFromJSON(json: any): V1Stock {
    return V1StockFromJSONTyped(json, false);
}

export function V1StockFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1Stock {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'deletedAt': !exists(json, 'deletedAt') ? undefined : (new Date(json['deletedAt'])),
        'stockID': !exists(json, 'stockID') ? undefined : json['stockID'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'country': !exists(json, 'country') ? undefined : json['country'],
        'category': !exists(json, 'category') ? undefined : json['category'],
        'market': !exists(json, 'market') ? undefined : json['market'],
    };
}

export function V1StockToJSON(value?: V1Stock | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'deletedAt': value.deletedAt === undefined ? undefined : (value.deletedAt.toISOString()),
        'stockID': value.stockID,
        'name': value.name,
        'country': value.country,
        'category': value.category,
        'market': value.market,
    };
}

