/* tslint:disable */
/* eslint-disable */
/**
 * Javis smart stock analysis API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1ThreePrimary
 */
export interface V1ThreePrimary {
    /**
     * 
     * @type {string}
     * @memberof V1ThreePrimary
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof V1ThreePrimary
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof V1ThreePrimary
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof V1ThreePrimary
     */
    deletedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof V1ThreePrimary
     */
    stockID?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ThreePrimary
     */
    date?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ThreePrimary
     */
    foreignTradeShares?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ThreePrimary
     */
    trustTradeShares?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ThreePrimary
     */
    dealerTradeShares?: string;
    /**
     * 
     * @type {string}
     * @memberof V1ThreePrimary
     */
    hedgingTradeShares?: string;
}

/**
 * Check if a given object implements the V1ThreePrimary interface.
 */
export function instanceOfV1ThreePrimary(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1ThreePrimaryFromJSON(json: any): V1ThreePrimary {
    return V1ThreePrimaryFromJSONTyped(json, false);
}

export function V1ThreePrimaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ThreePrimary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'deletedAt': !exists(json, 'deletedAt') ? undefined : (new Date(json['deletedAt'])),
        'stockID': !exists(json, 'stockID') ? undefined : json['stockID'],
        'date': !exists(json, 'date') ? undefined : json['date'],
        'foreignTradeShares': !exists(json, 'foreignTradeShares') ? undefined : json['foreignTradeShares'],
        'trustTradeShares': !exists(json, 'trustTradeShares') ? undefined : json['trustTradeShares'],
        'dealerTradeShares': !exists(json, 'dealerTradeShares') ? undefined : json['dealerTradeShares'],
        'hedgingTradeShares': !exists(json, 'hedgingTradeShares') ? undefined : json['hedgingTradeShares'],
    };
}

export function V1ThreePrimaryToJSON(value?: V1ThreePrimary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'deletedAt': value.deletedAt === undefined ? undefined : (value.deletedAt.toISOString()),
        'stockID': value.stockID,
        'date': value.date,
        'foreignTradeShares': value.foreignTradeShares,
        'trustTradeShares': value.trustTradeShares,
        'dealerTradeShares': value.dealerTradeShares,
        'hedgingTradeShares': value.hedgingTradeShares,
    };
}

